package com.kirito.planmer.bean;

public class Sign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_sign.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_sign.days
     *
     * @mbggenerated
     */
    private Integer days;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_sign.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_sign.id
     *
     * @return the value of pm_sign.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_sign.id
     *
     * @param id the value for pm_sign.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_sign.days
     *
     * @return the value of pm_sign.days
     *
     * @mbggenerated
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_sign.days
     *
     * @param days the value for pm_sign.days
     *
     * @mbggenerated
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_sign.user_id
     *
     * @return the value of pm_sign.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_sign.user_id
     *
     * @param userId the value for pm_sign.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}