package com.kirito.planmer.bean;

import java.util.Date;

public class SignInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_sign_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_sign_info.time
     *
     * @mbggenerated
     */
    private long time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_sign_info.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_sign_info.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_sign_info.id
     *
     * @return the value of pm_sign_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_sign_info.id
     *
     * @param id the value for pm_sign_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_sign_info.time
     *
     * @return the value of pm_sign_info.time
     *
     * @mbggenerated
     */
    public long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_sign_info.time
     *
     * @param time the value for pm_sign_info.time
     *
     * @mbggenerated
     */
    public void setTime(long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_sign_info.status
     *
     * @return the value of pm_sign_info.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_sign_info.status
     *
     * @param status the value for pm_sign_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_sign_info.user_id
     *
     * @return the value of pm_sign_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_sign_info.user_id
     *
     * @param userId the value for pm_sign_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}