package com.kirito.planmer.bean;

public class Task {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_task.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_task.star_time
     *
     * @mbggenerated
     */
    private Long starTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_task.end_time
     *
     * @mbggenerated
     */
    private Long endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_task.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_task.d_time
     *
     * @mbggenerated
     */
    private Long dTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_task.id
     *
     * @return the value of pm_task.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_task.id
     *
     * @param id the value for pm_task.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_task.star_time
     *
     * @return the value of pm_task.star_time
     *
     * @mbggenerated
     */
    public Long getStarTime() {
        return starTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_task.star_time
     *
     * @param starTime the value for pm_task.star_time
     *
     * @mbggenerated
     */
    public void setStarTime(Long starTime) {
        this.starTime = starTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_task.end_time
     *
     * @return the value of pm_task.end_time
     *
     * @mbggenerated
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_task.end_time
     *
     * @param endTime the value for pm_task.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_task.user_id
     *
     * @return the value of pm_task.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_task.user_id
     *
     * @param userId the value for pm_task.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_task.d_time
     *
     * @return the value of pm_task.d_time
     *
     * @mbggenerated
     */
    public Long getdTime() {
        return dTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_task.d_time
     *
     * @param dTime the value for pm_task.d_time
     *
     * @mbggenerated
     */
    public void setdTime(Long dTime) {
        this.dTime = dTime;
    }
}