package com.kirito.planmer.mapper;

import com.kirito.planmer.bean.SignInfo;

public interface SignInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_sign_info
     *
     * @mbggenerated
     */
    int insert(SignInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_sign_info
     *
     * @mbggenerated
     */
    int insertSelective(SignInfo record);

    /**
     * 获取用户签到信息
     * @param userId
     * @param startTime
     * @param endTime
     * @return
     */
    SignInfo getSignInfoByUser(int userId,long startTime,long endTime);
}