package com.kirito.planmer.mapper;

import com.kirito.planmer.bean.Sign;

public interface SignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_sign
     *
     * @mbggenerated
     */
    int insert(Sign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_sign
     *
     * @mbggenerated
     */
    int insertSelective(Sign record);

    Sign getUserSign(int userId);

    int updateUserSign(Sign sign);
}