package com.kirito.planmer.mapper;

import com.kirito.planmer.bean.User;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * 登录
     *
     * @return
     */
    User login(@Param("userName") String userName);

    User getUserById(int id);

    void  update(User record);

}