package com.kirito.planmer.mapper;

import com.kirito.planmer.bean.UserInfo;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user_info
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user_info
     *
     * @mbggenerated
     */
    int insertSelective(UserInfo record);
}